const data = {
    products:[
        {
            _id: '1',
            name: 'Lelush hair dye (blonde)',
            category:'hair dye',
            image:'/images/product-1.jpeg',
            price: 120,
            countInStock: 12,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: '2',
            name: 'Lelush hair dye (blonde)',
            category:'hair dye',
            image:'/images/product-1.jpeg',
            price: 100,
            countInStock: 12,
            brand: 'Nike',
            rating: 4,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: '3',
            name: 'Lelush hair dye (blonde)',
            category:'hair dye',
            image:'/images/product-1.jpeg',
            price: 130,
            countInStock: 12,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: '4',
            name: 'Lelush hair dye (blonde)',
            category:'hair dye',
            image:'/images/product-1.jpeg',
            price: 150,
            countInStock: 12,
            brand: 'Nike',
            rating: 5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: '5',
            name: 'Lelush hair dye (blonde)',
            category:'hair dye',
            image:'/images/product-1.jpeg',
            price: 120,
            countInStock: 12,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: '6',
            name: 'Lelush hair dye (blonde)',
            category:'hair dye',
            image:'/images/product-1.jpeg',
            price: 120,
            countInStock: 9,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },

    ],
}
export default data;